# Generated by Django 4.1 on 2022-09-03 12:49

from django.db import migrations, models
import tmp_app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageModel',
            fields=[
                ('file_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(default=tmp_app.utils.default_expiry)),
                ('url', models.URLField(blank=True)),
                ('file_path', models.CharField(max_length=100)),
            ],
        ),
    ]
